name: test
description: Just a place to practice
version: 0.0.1
environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  # eth_abi_codec:
  #   git:
  #     url: https://github.com/nbltrust/dart-eth-abi-codec
  #     ref: 2.0.0
  convert: ^3.1.1
  quiver: ^3.2.1
  # rlp: ^2.0.0
  # pointycastle: ^3.7.3
  # hex: ^0.2.0
